# Generated by Django 6.0.1 on 2026-02-04 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usercredential'),
        ('properties', '0004_tower_total_floors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('can_view', models.BooleanField(default=True)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'User Scope',
                'verbose_name_plural': 'User Scopes',
            },
        ),
        migrations.RemoveConstraint(
            model_name='tenantscope',
            name='ck_scope_exactly_one_ref',
        ),
        migrations.AddField(
            model_name='tenantscope',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='properties.site'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_json',
            field=models.JSONField(blank=True, default=dict, help_text='Custom profile data as JSON'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('BROKER', 'Broker'), ('TENANT', 'Tenant'), ('VIEWER', 'Viewer')], default='VIEWER', help_text="User's primary role in the system", max_length=20),
        ),
        migrations.AlterField(
            model_name='tenantscope',
            name='scope_type',
            field=models.CharField(choices=[('ORG', 'Org'), ('COMPANY', 'Company'), ('ENTITY', 'Entity'), ('SITE', 'Site')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='tenantscope',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('company__isnull', True), ('entity__isnull', True), ('org__isnull', False), ('site__isnull', True)), models.Q(('company__isnull', False), ('entity__isnull', True), ('org__isnull', True), ('site__isnull', True)), models.Q(('company__isnull', True), ('entity__isnull', False), ('org__isnull', True), ('site__isnull', True)), models.Q(('company__isnull', True), ('entity__isnull', True), ('org__isnull', True), ('site__isnull', False)), _connector='OR'), name='ck_scope_exactly_one_ref'),
        ),
        migrations.AddField(
            model_name='userscope',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userscope',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scopes', to='accounts.tenantscope'),
        ),
        migrations.AddField(
            model_name='userscope',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userscope',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scopes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userscope',
            index=models.Index(fields=['user', 'is_active'], name='accounts_us_user_id_1c137e_idx'),
        ),
        migrations.AddIndex(
            model_name='userscope',
            index=models.Index(fields=['scope', 'is_active'], name='accounts_us_scope_i_301f2e_idx'),
        ),
        migrations.AddConstraint(
            model_name='userscope',
            constraint=models.UniqueConstraint(fields=('user', 'scope'), name='uq_user_scope'),
        ),
    ]
