# Generated by Django 6.0.1 on 2026-02-05 10:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userscope_and_more'),
        ('properties', '0004_tower_total_floors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tenantscope',
            constraint=models.UniqueConstraint(condition=models.Q(('org__isnull', False)), fields=('org',), name='uq_scope_one_per_org'),
        ),
        migrations.AddConstraint(
            model_name='tenantscope',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False)), fields=('company',), name='uq_scope_one_per_company'),
        ),
        migrations.AddConstraint(
            model_name='tenantscope',
            constraint=models.UniqueConstraint(condition=models.Q(('entity__isnull', False)), fields=('entity',), name='uq_scope_one_per_entity'),
        ),
        migrations.AddConstraint(
            model_name='tenantscope',
            constraint=models.UniqueConstraint(condition=models.Q(('site__isnull', False)), fields=('site',), name='uq_scope_one_per_site'),
        ),
    ]
