# Generated by Django 6.0.1 on 2026-02-06 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tenantscope_uq_scope_one_per_org_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userscope',
            name='accounts_us_user_id_1c137e_idx',
        ),
        migrations.RemoveIndex(
            model_name='userscope',
            name='accounts_us_scope_i_301f2e_idx',
        ),
        migrations.RemoveConstraint(
            model_name='userscope',
            name='uq_user_scope',
        ),
        migrations.DeleteModel(
            name='UserScope',
        ),
    ]
