# Generated by Django 6.0.1 on 2026-02-06 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_userscope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='active_scope',
        ),
    ]
