# Generated by Django 6.0.1 on 2026-02-06 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_active_scope_from_profile'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usercredential',
            name='accounts_us_scope_i_357af2_idx',
        ),
        migrations.DeleteModel(
            name='UserCredential',
        ),
    ]
