# Generated by Django 6.0.1 on 2026-02-18 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_usercredential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='approval_cap_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Max lease value this role can approve (INR)', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='base_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_roles', to='accounts.role'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_approve_amendments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='can_approve_waivers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='can_modify_matrices',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='data_scope_property_ids',
            field=models.JSONField(blank=True, default=list, help_text='List of site IDs if data_scope_type=SELECTED'),
        ),
        migrations.AddField(
            model_name='role',
            name='data_scope_type',
            field=models.CharField(choices=[('ALL', 'All Properties'), ('SELECTED', 'Specific Properties')], default='ALL', max_length=20),
        ),
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='role',
            name='role_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('BUSINESS', 'Business (Internal)'), ('TENANT', 'Tenant'), ('READONLY', 'Read-only')], default='BUSINESS', max_length=20),
        ),
        migrations.AddField(
            model_name='role',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='invite_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='invite_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('PENDING', 'Pending'), ('SUSPENDED', 'Suspended')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='UserChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_changed', models.CharField(max_length=100)),
                ('old_value', models.CharField(blank=True, default='', max_length=500)),
                ('new_value', models.CharField(blank=True, default='', max_length=500)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_changes_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('module', models.CharField(choices=[('PROPERTY', 'Property & Unit Master'), ('TENANT', 'Tenant & Contact CRM'), ('LEASE', 'Lease & Amendments'), ('REVENUE', 'Rent Schedule & Revenue'), ('AR', 'Invoices & Receipts (AR)'), ('COLLECTIONS', 'Collections & Disputes'), ('DASHBOARD', 'Dashboards & Analytics'), ('APPROVALS', 'Approval Workflows & Matrices'), ('DOCUMENTS', 'Documents & Compliance / Audit Trail')], max_length=30)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_permissions', to='accounts.role')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['module'],
                'constraints': [models.UniqueConstraint(fields=('role', 'module'), name='uq_module_permission_role_module')],
            },
        ),
    ]
