# Generated by Django 6.0.1 on 2026-02-06 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_usercredential'),
        ('billing', '0002_ageingconfig_arglobalsettings_billingrule_creditrule_and_more'),
        ('properties', '0005_camcomponentgroup_camcomponent_sitecamconfig_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='cam_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_line_items', to='properties.camcomponent'),
        ),
        migrations.AlterField(
            model_name='ageingbucket',
            name='color_code',
            field=models.CharField(default='Gray', help_text='Color name for UI display: Blue, Purple, Orange, Red, Gray', max_length=20),
        ),
        migrations.AlterField(
            model_name='ageingbucket',
            name='label',
            field=models.CharField(help_text="Display label e.g., 'Current (0-30)', '31-60 Days'", max_length=50),
        ),
        migrations.AlterField(
            model_name='ageingbucket',
            name='to_days',
            field=models.PositiveIntegerField(blank=True, help_text='End of bucket range (inclusive). Null means open-ended (e.g., 121+ days)', null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='reason',
            field=models.CharField(choices=[('BILLING_ERROR', 'Billing Error'), ('RATE_ADJUSTMENT', 'Rate Adjustment'), ('GOODWILL', 'Goodwill'), ('SERVICE_ISSUE', 'Service Issue'), ('EARLY_TERMINATION', 'Early Termination'), ('PAYMENT_VARIANCE', 'Payment Variance'), ('OTHER', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='ageingconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ageingconfig',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenantscope'),
        ),
        migrations.AddField(
            model_name='ageingconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arglobalsettings',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arglobalsettings',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenantscope'),
        ),
        migrations.AddField(
            model_name='arglobalsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingrule',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_billing_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='billingrule',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenantscope'),
        ),
        migrations.AddField(
            model_name='billingrule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditrule',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenantscope'),
        ),
        migrations.AddField(
            model_name='creditrule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='credit_rule',
            field=models.ForeignKey(blank=True, help_text='Credit rule that triggered this credit note', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='billing.creditrule'),
        ),
        migrations.AddField(
            model_name='disputerule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disputerule',
            name='route_to_user',
            field=models.ForeignKey(blank=True, help_text='Specific user to route dispute to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_route_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disputerule',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenantscope'),
        ),
        migrations.AddField(
            model_name='disputerule',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitebillingconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitebillingconfig',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenantscope'),
        ),
        migrations.AddField(
            model_name='sitebillingconfig',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_config', to='properties.site'),
        ),
        migrations.AddField(
            model_name='sitebillingconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='ageingconfig',
            constraint=models.UniqueConstraint(fields=('scope',), name='unique_ageing_config_per_scope'),
        ),
        migrations.AddConstraint(
            model_name='arglobalsettings',
            constraint=models.UniqueConstraint(fields=('scope',), name='unique_ar_global_settings_per_scope'),
        ),
        migrations.AddConstraint(
            model_name='billingrule',
            constraint=models.UniqueConstraint(fields=('scope', 'rule_id'), name='unique_billing_rule_id_per_scope'),
        ),
        migrations.AddConstraint(
            model_name='creditrule',
            constraint=models.UniqueConstraint(fields=('scope', 'name'), name='unique_credit_rule_name_per_scope'),
        ),
        migrations.AddConstraint(
            model_name='disputerule',
            constraint=models.UniqueConstraint(fields=('scope', 'name'), name='unique_dispute_rule_name_per_scope'),
        ),
    ]
