# Generated by Django 6.0.1 on 2026-02-17 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_add_invoice_attachment_and_line_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='arglobalsettings',
            name='ar_ageing_bucket',
            field=models.ForeignKey(blank=True, help_text='Default AR ageing bucket mapping (e.g. Current 0-30)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_settings_default', to='billing.ageingbucket'),
        ),
        migrations.AddField(
            model_name='arglobalsettings',
            name='eligible_for_dunning',
            field=models.BooleanField(default=True, help_text='Include in dunning (payment reminder) workflow'),
        ),
        migrations.AddField(
            model_name='arglobalsettings',
            name='include_in_auto_email_batch',
            field=models.BooleanField(default=True, help_text='Include invoices in automated email batch'),
        ),
        migrations.AddField(
            model_name='arglobalsettings',
            name='revenue_recognition_rule',
            field=models.CharField(blank=True, choices=[('ACCRUAL_BASIS', 'Accrual Basis'), ('CASH_BASIS', 'Cash Basis'), ('HYBRID', 'Hybrid')], default='ACCRUAL_BASIS', help_text='How revenue is recognized for accounting', max_length=30),
        ),
    ]
