# Generated by Django 6.0.1 on 2026-02-18 04:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_usercredential'),
        ('billing', '0005_extend_arglobal_settings_accounting'),
        ('leases', '0006_leaseinsurancerequirement_indemnity_notes_and_more'),
        ('properties', '0005_camcomponentgroup_camcomponent_sitecamconfig_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentScheduleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('charge_type', models.CharField(choices=[('BASE_RENT', 'Base Rent'), ('CAM', 'CAM'), ('PARKING', 'Parking'), ('UTILITY', 'Utility'), ('TAX', 'Tax'), ('LATE_FEE', 'Late Fee'), ('ADJUSTMENT', 'Adjustment'), ('OTHER', 'Other')], default='BASE_RENT', max_length=20)),
                ('amount_before_tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('gst', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='GST/tax amount', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('amount_after_tax', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='amount_before_tax + gst', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('INVOICED', 'Invoiced'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('override_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Manual override of amount_after_tax', max_digits=14, null=True)),
                ('adjustment_reason', models.TextField(blank=True)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('escalation_applied', models.BooleanField(default=False)),
                ('escalation_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_schedule_lines', to='leases.agreement')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_schedule_lines', to='billing.invoice')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenantscope')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_schedule_lines', to='properties.unit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rent Schedule Line',
                'verbose_name_plural': 'Rent Schedule Lines',
                'ordering': ['agreement', 'period_start', 'period_end'],
                'indexes': [models.Index(fields=['agreement', 'period_start'], name='billing_ren_agreeme_a44d9d_idx'), models.Index(fields=['status'], name='billing_ren_status_0151d9_idx'), models.Index(fields=['due_date'], name='billing_ren_due_dat_3f98f7_idx')],
            },
        ),
    ]
