# Generated by Django 6.0.1 on 2026-02-24 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_company_entity_details_fields'),
        ('billing', '0006_add_rent_schedule_line'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrule',
            name='trigger_mode',
            field=models.CharField(choices=[('MANUAL', "Manual (alert, I'll apply)"), ('AUTO', 'Auto (fire immediately)')], default='MANUAL', help_text='MANUAL = create a pending action alert; AUTO = fire immediately', max_length=10),
        ),
        migrations.AddField(
            model_name='creditrule',
            name='trigger_mode',
            field=models.CharField(choices=[('MANUAL', "Manual (alert, I'll apply)"), ('AUTO', 'Auto (fire immediately)')], default='MANUAL', help_text='MANUAL = create a pending action alert; AUTO = fire immediately', max_length=10),
        ),
        migrations.AddField(
            model_name='disputerule',
            name='trigger_mode',
            field=models.CharField(choices=[('MANUAL', "Manual (alert, I'll apply)"), ('AUTO', 'Auto (fire immediately)')], default='MANUAL', help_text='MANUAL = create a pending action alert; AUTO = fire immediately', max_length=10),
        ),
        migrations.CreateModel(
            name='PendingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('rule_type', models.CharField(choices=[('BILLING', 'Billing Rule'), ('CREDIT', 'Credit Rule'), ('DISPUTE', 'Dispute Rule')], max_length=10)),
                ('object_type', models.CharField(choices=[('INVOICE', 'Invoice'), ('CREDIT_NOTE', 'Credit Note'), ('DISPUTE', 'Invoice Dispute')], max_length=20)),
                ('object_id', models.PositiveIntegerField(help_text='PK of the invoice/credit note/dispute')),
                ('action_description', models.TextField(help_text='Human-readable description of what will happen when applied')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPLIED', 'Applied'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=15)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, help_text='Optional note when applying or dismissing')),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_pending_actions', to=settings.AUTH_USER_MODEL)),
                ('billing_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_actions', to='billing.billingrule')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('credit_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_actions', to='billing.creditrule')),
                ('dispute_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_actions', to='billing.disputerule')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenantscope')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pending Action',
                'verbose_name_plural': 'Pending Actions',
                'ordering': ['-triggered_at'],
            },
        ),
    ]
