# Generated by Django 6.0.1 on 2026-02-24 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_company_entity_details_fields'),
        ('billing', '0007_add_trigger_mode_pending_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditrule',
            name='approval_level',
        ),
        migrations.AddField(
            model_name='creditrule',
            name='approval_role',
            field=models.ForeignKey(blank=True, help_text='Role that must approve credit notes triggered by this rule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_rules_requiring_approval', to='accounts.role'),
        ),
    ]
