# Generated by Django 6.0.1 on 2026-02-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_replace_credit_rule_approval_level_with_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingrule',
            name='rule_config',
        ),
        migrations.AddField(
            model_name='billingrule',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Flat amount (used when method is FLAT or PER_DAY)', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='billingrule',
            name='calculation_method',
            field=models.CharField(choices=[('FLAT', 'Flat Amount'), ('PERCENTAGE_OF_OUTSTANDING', '% of Outstanding'), ('PERCENTAGE_OF_RENT', '% of Rent'), ('PER_DAY', 'Per Day (flat × overdue days)')], default='FLAT', help_text='How the charge amount is calculated', max_length=40),
        ),
        migrations.AddField(
            model_name='billingrule',
            name='charge_type',
            field=models.CharField(choices=[('LATE_PAYMENT_FEE', 'Late Payment Fee'), ('INTEREST', 'Interest'), ('PENALTY', 'Penalty'), ('ADMINISTRATIVE_FEE', 'Administrative Fee'), ('CAM_RECONCILIATION', 'CAM Reconciliation'), ('OTHER', 'Other')], default='LATE_PAYMENT_FEE', help_text='Type of charge this rule raises', max_length=30),
        ),
        migrations.AddField(
            model_name='billingrule',
            name='gl_code',
            field=models.CharField(blank=True, help_text='GL account code for this charge e.g., 4100-LATE-FEE', max_length=50),
        ),
        migrations.AddField(
            model_name='billingrule',
            name='grace_period_days',
            field=models.PositiveIntegerField(default=0, help_text='Days after trigger event before rule fires (e.g., 7 = charge after 7 overdue days)'),
        ),
        migrations.AddField(
            model_name='billingrule',
            name='max_cap_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum charge amount (ceiling). Leave blank for no cap.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='billingrule',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Rate as a percentage e.g., 2.00 = 2% (used when method is PERCENTAGE_*)', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='billingrule',
            name='trigger_event',
            field=models.CharField(choices=[('OVERDUE', 'When Invoice is Overdue'), ('MONTHLY', 'Monthly (recurring)'), ('ON_INVOICE', 'On Invoice Generation'), ('MANUAL_ONLY', 'Manual Trigger Only')], default='OVERDUE', help_text='Event that triggers this rule', max_length=20),
        ),
        migrations.AlterField(
            model_name='billingrule',
            name='name',
            field=models.CharField(help_text="Rule name e.g., 'Late Payment Fee 2%'", max_length=100),
        ),
    ]
