# Generated by Django 5.1.2 on 2026-02-26 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_sitebillingconfig_cleanup_and_invoice_flags'),
        ('leases', '0010_leaseamendment_amendment_data'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='creditrule',
            name='unique_credit_rule_name_per_scope',
        ),
        migrations.RemoveConstraint(
            model_name='disputerule',
            name='unique_dispute_rule_name_per_scope',
        ),
        migrations.AddField(
            model_name='billingrule',
            name='agreement',
            field=models.ForeignKey(blank=True, help_text='If set, this rule only applies to this specific agreement', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_rules', to='leases.agreement'),
        ),
        migrations.AddField(
            model_name='creditrule',
            name='agreement',
            field=models.ForeignKey(blank=True, help_text='If set, this rule only applies to this specific agreement', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_rules', to='leases.agreement'),
        ),
        migrations.AddField(
            model_name='disputerule',
            name='agreement',
            field=models.ForeignKey(blank=True, help_text='If set, this rule only applies to this specific agreement', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispute_rules', to='leases.agreement'),
        ),
    ]
