# Generated by Django 6.0.1 on 2026-02-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_site_building_street_site_contract_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='allowed_use',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='floor',
            name='floor_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='floor',
            name='leasing_type',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='floor',
            name='max_units_allowed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
