# Generated by Django 6.0.1 on 2026-02-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_floor_allowed_use_floor_floor_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tower',
            name='total_floors',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
