# Generated by Django 6.0.1 on 2026-02-06 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_usercredential'),
        ('properties', '0004_tower_total_floors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CAMComponentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(help_text="Group name e.g., 'Core CAM', 'Security', 'Housekeeping', 'Utilities'", max_length=100)),
                ('code', models.SlugField(help_text='Unique code for the group')),
                ('description', models.TextField(blank=True, help_text='Description of this component group')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order of groups')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenantscope')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CAM Component Group',
                'verbose_name_plural': 'CAM Component Groups',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CAMComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(help_text="Component name e.g., 'HVAC Maintenance', 'Security Personnel'", max_length=100)),
                ('code', models.SlugField(help_text='Unique code for the component')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the component')),
                ('rate_logic', models.CharField(choices=[('PER_SQFT_MONTHLY', 'Per Sq.Ft - Monthly'), ('PER_SQFT_ANNUAL', 'Per Sq.Ft - Annual'), ('SHARE_OF_TOTAL', 'Share of Total'), ('FIXED_MONTHLY', 'Fixed Monthly'), ('FIXED_ANNUAL', 'Fixed Annual'), ('PER_UNIT', 'Per Unit')], default='PER_SQFT_MONTHLY', help_text='How the rate is calculated', max_length=20)),
                ('default_rate', models.DecimalField(decimal_places=2, default=0, help_text='Default rate value', max_digits=14)),
                ('area_basis', models.CharField(choices=[('CHARGEABLE_AREA', 'Chargeable Area'), ('CARPET_AREA', 'Carpet Area'), ('SUPER_BUILTUP', 'Super Builtup Area'), ('LEASABLE_AREA', 'Leasable Area')], default='CHARGEABLE_AREA', help_text='Which area measurement to use', max_length=20)),
                ('rate_type', models.CharField(choices=[('FIXED', 'Fixed'), ('INDEX_LINKED', 'Index-linked')], default='FIXED', help_text='Whether rate is fixed or index-linked', max_length=20)),
                ('rate_unit', models.CharField(default='sq. ft. / month', help_text='Unit of measurement for display', max_length=50)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=18.0, help_text='GST rate percentage', max_digits=5)),
                ('index_name', models.CharField(blank=True, help_text='Index name for INDEX_LINKED rate type', max_length=100)),
                ('utilities_treatment', models.CharField(choices=[('INCLUDED', 'Included'), ('METERED', 'Metered'), ('BLENDED', 'Blended')], default='INCLUDED', help_text='How utility charges related to this component are handled', max_length=20)),
                ('fit_out_applicable', models.BooleanField(default=True, help_text='Whether this component applies during fit-out period')),
                ('post_handover_applicable', models.BooleanField(default=True, help_text='Whether this component applies post-handover')),
                ('follow_cam_template', models.BooleanField(default=False, help_text='Follow CAM template for escalation')),
                ('follow_parking_template', models.BooleanField(default=False, help_text='Follow parking template for escalation')),
                ('gl_code', models.CharField(blank=True, help_text='GL code for this component', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenantscope')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(help_text='Category group for this component', on_delete=django.db.models.deletion.PROTECT, related_name='components', to='properties.camcomponentgroup')),
            ],
            options={
                'verbose_name': 'CAM Component',
                'verbose_name_plural': 'CAM Components',
                'ordering': ['group__sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SiteCAMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('override_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Override rate for this site (null = use component default)', max_digits=14, null=True)),
                ('override_area_basis', models.CharField(blank=True, choices=[('CHARGEABLE_AREA', 'Chargeable Area'), ('CARPET_AREA', 'Carpet Area'), ('SUPER_BUILTUP', 'Super Builtup Area'), ('LEASABLE_AREA', 'Leasable Area')], help_text='Override area basis for this site', max_length=20)),
                ('override_gst_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Override GST rate for this site', max_digits=5, null=True)),
                ('fit_out_applicable', models.BooleanField(default=True, help_text='Whether this component applies during fit-out at this site')),
                ('post_handover_applicable', models.BooleanField(default=True, help_text='Whether this component applies post-handover at this site')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this component is active for this site')),
                ('gl_code_override', models.CharField(blank=True, help_text='Site-specific GL code override', max_length=50)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_configs', to='properties.camcomponent')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenantscope')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cam_configs', to='properties.site')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site CAM Configuration',
                'verbose_name_plural': 'Site CAM Configurations',
                'ordering': ['site', 'component__group__sort_order', 'component__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='camcomponentgroup',
            constraint=models.UniqueConstraint(fields=('scope', 'code'), name='unique_cam_group_code_per_scope'),
        ),
        migrations.AddConstraint(
            model_name='camcomponent',
            constraint=models.UniqueConstraint(fields=('scope', 'code'), name='unique_cam_component_code_per_scope'),
        ),
        migrations.AddConstraint(
            model_name='sitecamconfig',
            constraint=models.UniqueConstraint(fields=('site', 'component'), name='unique_site_cam_component'),
        ),
    ]
