# Generated by Django 6.0.1 on 2026-02-18 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_role_approval_cap_amount_role_base_on_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='DRAFT', max_length=20)),
                ('lease_value_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum lease value (INR) to trigger this rule', max_digits=14, null=True)),
                ('lease_value_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum lease value (INR) to trigger this rule (null = no upper limit)', max_digits=14, null=True)),
                ('tenant_types', models.JSONField(blank=True, default=list, help_text='List of TenantType values; empty = applies to all')),
                ('lease_term_min_months', models.PositiveIntegerField(blank=True, help_text='Minimum lease term in months', null=True)),
                ('lease_term_max_months', models.PositiveIntegerField(blank=True, help_text='Maximum lease term in months (null = no upper limit)', null=True)),
                ('overall_sla_hours', models.PositiveIntegerField(default=48, help_text='Total SLA in hours across all approval levels')),
                ('enable_escalations', models.BooleanField(default=False)),
                ('escalate_after_hours', models.PositiveIntegerField(default=24, help_text='Hours of inaction before escalation triggers')),
                ('send_escalation_notification', models.BooleanField(default=False)),
                ('parallel_approvals_same_level', models.BooleanField(default=False, help_text='If True, all approvers at same level can approve in parallel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('escalate_to_role', models.ForeignKey(blank=True, help_text='Role to escalate to if no action within escalate_after_hours', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_rules', to='accounts.role')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_rules', to='accounts.tenantscope')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['lease_value_min', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRuleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('ACTIVATED', 'Activated'), ('DEACTIVATED', 'Deactivated'), ('DELETED', 'Deleted')], max_length=20)),
                ('detail', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='approvals.approvalrule')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_rule_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('level', models.PositiveSmallIntegerField(help_text='1 = L1 (first approver), 2 = L2, etc.')),
                ('approval_required', models.BooleanField(default=True, help_text="If False, this level is informational only (notify but don't block)")),
                ('sla_hours', models.PositiveIntegerField(default=24, help_text='SLA for this individual level in hours')),
                ('allow_auto_skip_if_vacant', models.BooleanField(default=False, help_text='Skip this level automatically if no user has this role')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_levels', to='accounts.role')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='approvals.approvalrule')),
            ],
            options={
                'ordering': ['rule', 'level'],
                'constraints': [models.UniqueConstraint(fields=('rule', 'level'), name='uq_approval_rule_level')],
            },
        ),
    ]
