# Generated by Django 6.0.1 on 2026-02-04 06:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('invoice_generate_rule', models.CharField(choices=[('1ST_DAY_OF_MONTH', '1st Day of Month'), ('5TH_DAY_OF_MONTH', '5th Day of Month'), ('10TH_DAY_OF_MONTH', '10th Day of Month'), ('ON_COMMENCEMENT_DATE', 'On Commencement Date')], default='1ST_DAY_OF_MONTH', max_length=30)),
                ('grace_days', models.PositiveIntegerField(default=7)),
                ('late_fee_flat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('late_fee_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('interest_annual_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gst_applicable', models.BooleanField(default=True)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5)),
            ],
            options={
                'verbose_name': 'Lease Billing',
                'verbose_name_plural': 'Lease Billings',
            },
        ),
        migrations.CreateModel(
            name='LeaseCAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('allocation_basis', models.CharField(choices=[('PRO_RATA', 'Pro-rata (based on area)'), ('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage of Rent')], default='PRO_RATA', max_length=20)),
                ('per_sqft_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('fixed_amount_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('percentage_value', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of rent', max_digits=5, null=True)),
                ('monthly_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
            ],
            options={
                'verbose_name': 'Lease CAM',
                'verbose_name_plural': 'Lease CAMs',
            },
        ),
        migrations.CreateModel(
            name='LeaseDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('months_equivalent', models.PositiveIntegerField(blank=True, help_text='Number of months rent equivalent', null=True)),
                ('held_by', models.CharField(blank=True, max_length=255)),
                ('refund_conditions', models.TextField(blank=True)),
                ('interest_bearing', models.BooleanField(default=False)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'Lease Deposit',
                'verbose_name_plural': 'Lease Deposits',
            },
        ),
        migrations.CreateModel(
            name='LeaseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('document_type', models.CharField(choices=[('AGREEMENT', 'Lease Agreement'), ('AMENDMENT', 'Amendment'), ('ADDENDUM', 'Addendum'), ('NOTICE', 'Notice'), ('RENEWAL', 'Renewal'), ('OTHER', 'Other')], default='AGREEMENT', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='lease_documents/%Y/%m/')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Lease Document',
                'verbose_name_plural': 'Lease Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaseEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('escalation_type', models.CharField(choices=[('FIXED_PERCENT', 'Fixed Percentage'), ('CPI_INDEX', 'CPI Index'), ('MARKET_RATE', 'Market Rate'), ('STEP_UP', 'Step Up'), ('NONE', 'No Escalation')], default='FIXED_PERCENT', max_length=20)),
                ('escalation_value', models.DecimalField(blank=True, decimal_places=2, help_text='Escalation percentage (e.g., 5.00 for 5%)', max_digits=5, null=True)),
                ('escalation_frequency_months', models.PositiveIntegerField(default=12, help_text='How often escalation is applied (in months)')),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lease Escalation',
                'verbose_name_plural': 'Lease Escalations',
            },
        ),
        migrations.CreateModel(
            name='LeaseFinancials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('base_rent_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('rate_per_sqft_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('annual_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('billing_frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('HALF_YEARLY', 'Half Yearly'), ('ANNUALLY', 'Annually')], default='MONTHLY', max_length=20)),
                ('payment_due_date', models.CharField(choices=[('1ST_DAY_OF_MONTH', '1st Day of Month'), ('5TH_DAY_OF_MONTH', '5th Day of Month'), ('10TH_DAY_OF_MONTH', '10th Day of Month'), ('15TH_DAY_OF_MONTH', '15th Day of Month'), ('ON_COMMENCEMENT_DATE', 'On Lease Start Date')], default='1ST_DAY_OF_MONTH', max_length=30)),
                ('first_rent_due_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='INR', max_length=3)),
            ],
            options={
                'verbose_name': 'Lease Financials',
                'verbose_name_plural': 'Lease Financials',
            },
        ),
        migrations.CreateModel(
            name='LeaseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('note_text', models.TextField()),
            ],
            options={
                'verbose_name': 'Lease Note',
                'verbose_name_plural': 'Lease Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaseRentFree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('rent_free_start_date', models.DateField(blank=True, null=True)),
                ('rent_free_days', models.PositiveIntegerField(blank=True, null=True)),
                ('rent_free_end_date', models.DateField(blank=True, null=True)),
                ('fitout_start_date', models.DateField(blank=True, null=True)),
                ('fitout_end_date', models.DateField(blank=True, null=True)),
                ('cam_during_fitout', models.BooleanField(default=False, help_text='Whether CAM is charged during fit-out period')),
                ('fitout_completion_cert_required', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Lease Rent Free Period',
                'verbose_name_plural': 'Lease Rent Free Periods',
            },
        ),
        migrations.CreateModel(
            name='LeaseTermDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('commencement_date', models.DateField(blank=True, null=True)),
                ('initial_term_months', models.PositiveIntegerField(blank=True, help_text='Lease duration in months', null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('lock_in_start_date', models.DateField(blank=True, null=True)),
                ('lock_in_end_date', models.DateField(blank=True, null=True)),
                ('lock_in_months', models.PositiveIntegerField(blank=True, null=True)),
                ('notice_renewal_days', models.PositiveIntegerField(default=90, help_text='Days before expiry to notify for renewal')),
                ('notice_landlord_days', models.PositiveIntegerField(default=90, help_text='Days notice required by landlord')),
                ('notice_tenant_days', models.PositiveIntegerField(default=90, help_text='Days notice required by tenant')),
            ],
            options={
                'verbose_name': 'Lease Term Dates',
                'verbose_name_plural': 'Lease Term Dates',
            },
        ),
        migrations.CreateModel(
            name='LeaseTermination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('termination_clause', models.TextField(blank=True)),
                ('governing_law', models.CharField(default='India', max_length=100)),
                ('jurisdiction', models.CharField(blank=True, max_length=100)),
                ('break_date', models.DateField(blank=True, null=True)),
                ('break_penalty', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('break_penalty_type', models.CharField(blank=True, help_text="e.g., 'Months Rent', 'Fixed Amount'", max_length=50)),
                ('break_notice_days', models.PositiveIntegerField(blank=True, help_text='Days notice required for break', null=True)),
            ],
            options={
                'verbose_name': 'Lease Termination',
                'verbose_name_plural': 'Lease Terminations',
            },
        ),
        migrations.CreateModel(
            name='UnitAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('allocation_mode', models.CharField(choices=[('FULL', 'Full Unit'), ('PARTIAL', 'Partial Unit')], default='FULL', max_length=10)),
                ('allocated_area_sqft', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('monthly_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
            ],
            options={
                'verbose_name': 'Unit Allocation',
                'verbose_name_plural': 'Unit Allocations',
            },
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('lease_id', models.CharField(help_text='Human-readable lease identifier (e.g., LSE-2024-001)', max_length=50)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated')], default='DRAFT', max_length=20)),
                ('agreement_type', models.CharField(choices=[('COMMERCIAL_RETAIL', 'Commercial Retail Lease'), ('OFFICE', 'Office Lease'), ('WAREHOUSE', 'Warehouse Lease'), ('INDUSTRIAL', 'Industrial Lease'), ('RESIDENTIAL', 'Residential Lease')], default='OFFICE', max_length=30)),
                ('landlord_entity', models.CharField(blank=True, max_length=255)),
                ('ref_code', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lease Agreement',
                'verbose_name_plural': 'Lease Agreements',
                'ordering': ['-created_at'],
            },
        ),
    ]
