# Generated by Django 6.0.1 on 2026-02-04 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_usercredential'),
        ('leases', '0001_initial'),
        ('properties', '0004_tower_total_floors'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='primary_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_lease_agreements', to='tenants.tenantcontact'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenantscope'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lease_agreements', to='properties.site'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lease_agreements', to='tenants.tenantcompany'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leasebilling',
            name='agreement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='leases.agreement'),
        ),
        migrations.AddField(
            model_name='leasebilling',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leasebilling',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenantscope'),
        ),
        migrations.AddField(
            model_name='leasebilling',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leasecam',
            name='agreement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cam', to='leases.agreement'),
        ),
        migrations.AddField(
            model_name='leasecam',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leasecam',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenantscope'),
        ),
        migrations.AddField(
            model_name='leasecam',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leasedeposit',
            name='agreement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deposit', to='leases.agreement'),
        ),
        migrations.AddField(
            model_name='leasedeposit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leasedeposit',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenantscope'),
        ),
        migrations.AddField(
            model_name='leasedeposit',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leasedocument',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='leases.agreement'),
        ),
        migrations.AddField(
            model_name='leasedocument',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leasedocument',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenantscope'),
        ),
        migrations.AddField(
            model_name='leasedocument',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaseescalation',
            name='agreement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escalation', to='leases.agreement'),
        ),
        migrations.AddField(
            model_name='leaseescalation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaseescalation',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenantscope'),
        ),
        migrations.AddField(
            model_name='leaseescalation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leasefinancials',
            name='agreement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='leases.agreement'),
        ),
        migrations.AddField(
            model_name='leasefinancials',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leasefinancials',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenantscope'),
        ),
        migrations.AddField(
            model_name='leasefinancials',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leasenote',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_list', to='leases.agreement'),
        ),
        migrations.AddField(
            model_name='leasenote',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leasenote',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenantscope'),
        ),
        migrations.AddField(
            model_name='leasenote',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaserentfree',
            name='agreement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rent_free', to='leases.agreement'),
        ),
        migrations.AddField(
            model_name='leaserentfree',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaserentfree',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenantscope'),
        ),
        migrations.AddField(
            model_name='leaserentfree',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leasetermdates',
            name='agreement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='term_dates', to='leases.agreement'),
        ),
        migrations.AddField(
            model_name='leasetermdates',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leasetermdates',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenantscope'),
        ),
        migrations.AddField(
            model_name='leasetermdates',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leasetermination',
            name='agreement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='termination', to='leases.agreement'),
        ),
        migrations.AddField(
            model_name='leasetermination',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leasetermination',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenantscope'),
        ),
        migrations.AddField(
            model_name='leasetermination',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unitallocation',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_allocations', to='leases.agreement'),
        ),
        migrations.AddField(
            model_name='unitallocation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unitallocation',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenantscope'),
        ),
        migrations.AddField(
            model_name='unitallocation',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lease_allocations', to='properties.unit'),
        ),
        migrations.AddField(
            model_name='unitallocation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='agreement',
            constraint=models.UniqueConstraint(fields=('scope', 'lease_id', 'version_number'), name='unique_lease_id_version_per_scope'),
        ),
        migrations.AddConstraint(
            model_name='unitallocation',
            constraint=models.UniqueConstraint(fields=('agreement', 'unit'), name='unique_unit_per_agreement'),
        ),
    ]
