# Generated by Django 6.0.1 on 2026-02-11 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_usercredential'),
        ('leases', '0003_leaseescalation_apply_to_cam_and_more'),
        ('properties', '0005_camcomponentgroup_camcomponent_sitecamconfig_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='unitallocation',
            name='unique_unit_per_agreement',
        ),
        migrations.AddField(
            model_name='unitallocation',
            name='allocation_level',
            field=models.CharField(choices=[('SITE', 'Site'), ('TOWER', 'Tower'), ('FLOOR', 'Floor'), ('UNIT', 'Unit')], default='UNIT', max_length=10),
        ),
        migrations.AddField(
            model_name='unitallocation',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lease_allocations', to='properties.floor'),
        ),
        migrations.AddField(
            model_name='unitallocation',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lease_allocations', to='properties.site'),
        ),
        migrations.AddField(
            model_name='unitallocation',
            name='tower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lease_allocations', to='properties.tower'),
        ),
        migrations.AlterField(
            model_name='unitallocation',
            name='allocation_mode',
            field=models.CharField(choices=[('FULL', 'Full'), ('PARTIAL', 'Partial')], default='FULL', max_length=10),
        ),
        migrations.AlterField(
            model_name='unitallocation',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lease_allocations', to='properties.unit'),
        ),
        migrations.AddConstraint(
            model_name='unitallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('site__isnull', False), ('tower__isnull', True), ('floor__isnull', True), ('unit__isnull', True)), models.Q(('site__isnull', True), ('tower__isnull', False), ('floor__isnull', True), ('unit__isnull', True)), models.Q(('site__isnull', True), ('tower__isnull', True), ('floor__isnull', False), ('unit__isnull', True)), models.Q(('site__isnull', True), ('tower__isnull', True), ('floor__isnull', True), ('unit__isnull', False)), _connector='OR'), name='ck_alloc_single_target'),
        ),
        migrations.AddConstraint(
            model_name='unitallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('allocation_level', 'SITE'), ('site__isnull', False), ('tower__isnull', True), ('floor__isnull', True), ('unit__isnull', True)), models.Q(('allocation_level', 'TOWER'), ('site__isnull', True), ('tower__isnull', False), ('floor__isnull', True), ('unit__isnull', True)), models.Q(('allocation_level', 'FLOOR'), ('site__isnull', True), ('tower__isnull', True), ('floor__isnull', False), ('unit__isnull', True)), models.Q(('allocation_level', 'UNIT'), ('site__isnull', True), ('tower__isnull', True), ('floor__isnull', True), ('unit__isnull', False)), _connector='OR'), name='ck_alloc_level_target_match'),
        ),
        migrations.AddConstraint(
            model_name='unitallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('site__isnull', False)), fields=('agreement', 'site'), name='uq_alloc_agreement_site'),
        ),
        migrations.AddConstraint(
            model_name='unitallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('tower__isnull', False)), fields=('agreement', 'tower'), name='uq_alloc_agreement_tower'),
        ),
        migrations.AddConstraint(
            model_name='unitallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('floor__isnull', False)), fields=('agreement', 'floor'), name='uq_alloc_agreement_floor'),
        ),
        migrations.AddConstraint(
            model_name='unitallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('unit__isnull', False)), fields=('agreement', 'unit'), name='uq_alloc_agreement_unit'),
        ),
    ]
