# Generated by Django 6.0.1 on 2026-02-11 14:02

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0004_remove_unitallocation_unique_unit_per_agreement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaserentfree',
            name='extended_buffer_charge_percent',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('50.00'), help_text='Charge percentage during extended buffer days', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='leaserentfree',
            name='extended_buffer_days',
            field=models.PositiveIntegerField(blank=True, help_text='Additional days after rent-free period where partial rent is charged', null=True),
        ),
    ]
