# Generated by Django 6.0.1 on 2026-02-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0005_leaserentfree_extended_buffer_charge_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseinsurancerequirement',
            name='indemnity_notes',
            field=models.TextField(blank=True, help_text='Indemnity clause text / notes'),
        ),
        migrations.AddField(
            model_name='leaseinsurancerequirement',
            name='restore_details',
            field=models.TextField(blank=True, help_text='Free-text reinstatement details (e.g., Return to original white box condition)'),
        ),
        migrations.AddField(
            model_name='leasesubletsignage',
            name='signage_area_unit',
            field=models.CharField(choices=[('SQFT', 'Square Feet'), ('SQM', 'Square Meters')], default='SQFT', help_text='Unit for signage area (SQFT or SQM)', max_length=10),
        ),
        migrations.AlterField(
            model_name='leasesubletsignage',
            name='signage_area_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Allowed signage area (unit in signage_area_unit)', max_digits=10, null=True),
        ),
    ]
