# Generated by Django 6.0.1 on 2026-02-18 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_company_entity_details_fields'),
        ('leases', '0006_leaseinsurancerequirement_indemnity_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(help_text="Structure name e.g., 'Standard Commercial Lease'", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the structure')),
                ('is_default', models.BooleanField(default=False, help_text='Use as default for new agreements')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenantscope')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agreement Structure',
                'verbose_name_plural': 'Agreement Structures',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgreementSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(help_text="Section title e.g., 'Rent & Payment'", max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='leases.agreementsection')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenantscope')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='leases.agreementstructure')),
            ],
            options={
                'verbose_name': 'Agreement Section',
                'verbose_name_plural': 'Agreement Sections',
                'ordering': ['structure', 'sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='agreement',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreements', to='leases.agreementstructure'),
        ),
        migrations.AddConstraint(
            model_name='agreementstructure',
            constraint=models.UniqueConstraint(fields=('scope', 'name'), name='unique_agreement_structure_name_per_scope'),
        ),
        migrations.AddConstraint(
            model_name='agreementsection',
            constraint=models.UniqueConstraint(fields=('structure', 'name'), name='unique_section_name_per_structure'),
        ),
    ]
