# Generated by Django 5.1.2 on 2026-02-24 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_company_entity_details_fields'),
        ('leases', '0007_add_agreement_structure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('step_order', models.PositiveIntegerField(default=1, help_text='Order of this approval step')),
                ('step_name', models.CharField(help_text='Name of approval step (e.g., L1 - Finance Manager)', max_length=100)),
                ('step_description', models.TextField(blank=True, help_text='Description of what this step entails')),
                ('approval_required', models.BooleanField(default=True, help_text='If False, this is informational and does not block activation')),
                ('approver_role', models.CharField(blank=True, help_text='Role required for approval', max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('actioned_at', models.DateTimeField(blank=True, help_text='When action was taken', null=True)),
                ('comments', models.TextField(blank=True, help_text='Approver comments')),
                ('due_date', models.DateField(blank=True, help_text='Deadline for this approval step', null=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='leases.agreement')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreement_approvals', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenantscope')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agreement Approval',
                'verbose_name_plural': 'Agreement Approvals',
                'ordering': ['agreement', 'step_order'],
                'constraints': [models.UniqueConstraint(fields=('agreement', 'step_order'), name='unique_agreement_approval_step')],
            },
        ),
    ]
