# Generated by Django 5.1.2 on 2026-02-24 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0008_agreementapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='clause_mapping_draft',
            field=models.JSONField(blank=True, default=list, help_text='Draft clause-to-section mapping for this agreement. Used to auto-sync ClauseUsage records when the agreement is submitted.'),
        ),
    ]
