# Generated by Django 5.1.2 on 2026-03-07 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leases', '0010_leaseamendment_amendment_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='clause_mapping_draft',
        ),
    ]
