# Generated by Django 6.0.1 on 2026-02-04 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_usercredential'),
        ('leases', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClauseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='clauses.clausecategory')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenantscope')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clause Category',
                'verbose_name_plural': 'Clause Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('clause_id', models.CharField(help_text='Auto-generated clause identifier', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('applies_to', models.CharField(choices=[('COMMERCIAL', 'Commercial'), ('RESIDENTIAL', 'Residential'), ('ALL', 'All')], default='ALL', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('INACTIVE', 'Inactive')], default='DRAFT', max_length=20)),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('current_minor_version', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_clauses', to=settings.AUTH_USER_MODEL)),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenantscope')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clauses', to='clauses.clausecategory')),
            ],
            options={
                'verbose_name': 'Clause',
                'verbose_name_plural': 'Clauses',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ClauseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('PDF', 'PDF'), ('DOCX', 'Word Document'), ('XLSX', 'Excel Spreadsheet'), ('IMAGE', 'Image'), ('OTHER', 'Other')], default='PDF', max_length=20)),
                ('file', models.FileField(upload_to='clause_documents/%Y/%m/')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenantscope')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_clause_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clause Document',
                'verbose_name_plural': 'Clause Documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClauseDocumentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('clause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_links', to='clauses.clause')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clause_links', to='clauses.clausedocument')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenantscope')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clause Document Link',
                'verbose_name_plural': 'Clause Document Links',
            },
        ),
        migrations.CreateModel(
            name='ClauseVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('major_version', models.PositiveIntegerField(default=1)),
                ('minor_version', models.PositiveIntegerField(default=0)),
                ('version_status', models.CharField(choices=[('CURRENT', 'Current'), ('ARCHIVED', 'Archived')], default='CURRENT', max_length=20)),
                ('change_summary', models.TextField(blank=True, help_text='Summary of changes in this version')),
                ('body_text', models.TextField(blank=True, help_text='Main clause text content')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Structured clause configuration (renewal, termination, etc.)')),
                ('bump_type', models.CharField(blank=True, choices=[('MAJOR', 'Major (v1.0 → v2.0)'), ('MINOR', 'Minor (v1.0 → v1.1)')], max_length=10, null=True)),
                ('clause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='clauses.clause')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenantscope')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clause Version',
                'verbose_name_plural': 'Clause Versions',
                'ordering': ['-major_version', '-minor_version'],
            },
        ),
        migrations.CreateModel(
            name='ClauseUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('custom_config', models.JSONField(blank=True, default=dict, help_text='Custom configuration overrides for this agreement')),
                ('custom_body_text', models.TextField(blank=True, help_text='Custom body text for this agreement')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clause_usages', to='leases.agreement')),
                ('clause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='clauses.clause')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='accounts.tenantscope')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('clause_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='clauses.clauseversion')),
            ],
            options={
                'verbose_name': 'Clause Usage',
                'verbose_name_plural': 'Clause Usages',
            },
        ),
        migrations.AddConstraint(
            model_name='clausecategory',
            constraint=models.UniqueConstraint(fields=('scope', 'name'), name='unique_clause_category_name_per_scope'),
        ),
        migrations.AddConstraint(
            model_name='clause',
            constraint=models.UniqueConstraint(fields=('scope', 'clause_id'), name='unique_clause_id_per_scope'),
        ),
        migrations.AddConstraint(
            model_name='clausedocumentlink',
            constraint=models.UniqueConstraint(fields=('document', 'clause'), name='unique_document_clause_link'),
        ),
        migrations.AddConstraint(
            model_name='clauseversion',
            constraint=models.UniqueConstraint(fields=('clause', 'major_version', 'minor_version'), name='unique_clause_version'),
        ),
        migrations.AddConstraint(
            model_name='clauseusage',
            constraint=models.UniqueConstraint(fields=('clause', 'agreement'), name='unique_clause_per_agreement'),
        ),
    ]
