# Generated by Django 6.0.1 on 2026-02-18 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clauses', '0001_initial'),
        ('leases', '0007_add_agreement_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='clauseusage',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Section within agreement structure where this clause appears', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clause_usages', to='leases.agreementsection'),
        ),
    ]
